### ISSUE TITLE
Not working on Raspberry Pi 3

### ISSUE THREAD

**Issue by alessioxp** [oxplot/tjtag-pi#3]
When I launch "sudo ./tjtag -probeonly", I get this output:

pi@raspberrypi:~/tjtag-pi $ sudo ./tjtag -probeonly

==============================================
 EJTAG Debrick Utility v3.0.1 Tornado-MOD 
==============================================

Probing bus ... Done

Instruction Length set to 5

CPU Chip ID: 00000000000000000000000000000000 (00000000)
*** Unknown or NO CPU Chip ID Detected ***

*** Possible Causes:
    1) Device is not Connected.
    2) Device is not Powered On.
    3) Improper JTAG Cable.
    4) Unrecognized CPU Chip ID.

I checked wiring many, many times but it still doesn't work...

**Comment by ryanisaacs** [comment]
I'm getting the same all 0 chip ID. I'm trying to connect to a WRT54GL, using the same wiring shown in the image. After I soldered on my header, I was getting 3.3V on pins 1,3,5,7,9 of the JP1 (JTAG), and 0V on all the other pins. I believe this is what I should see.

I also tried -probeonly with several /delay values.

**Comment by deciacco** [comment]
I was not able to get it to work on RPI 3 either after checking and rechecking wiring and trying it on a wrt54G v4 and on a wrt54gl v1.1...is there something else that needs to be done on a rpi3?

**Comment by deciacco** [comment]
I dug up my old rpi model b and it worked great, so I can confirm this does not work on rpi 3.

**Comment by acidice333** [comment]
I recently had to reflash my WRT54G and it wouldnt work on my 3B+, so I whipped out the older RPI and it worked fine.    

I did manage to get it working on the 3 though.
Here's my fork
https://github.com/acidice333/tjtag-pi

**Comment by oxplot** [comment]
Thanks. Added it to readme.

**Comment by Eskander** [comment]
@acidice333's fork makes `tjtag-pi` work on RPi 2B as well.
@oxplot please add note about RPi 2 in readme as well.
and thanks for everyone
